import pandas as pd
import streamlit as st

from utils.charts import signal_chart
from utils.data import NAME_MAP, TICKERS, compute_features, compute_signals, load_data


def render():
    df = compute_features(load_data())

    st.markdown(
        """
    <div class="hero">
        <div class="hero-eyebrow">Technical Signals</div>
        <h1>Signal <span>Explorer</span></h1>
        <p class="hero-sub">
            Explore moving-average crossover signals, including Golden Cross and Death Cross events,
            across all four stocks. These are analytical observations rather than trading recommendations.
        </p>
        <div class="hero-badges">
            <span class="hero-badge green">Buy Signals</span>
            <span class="hero-badge red">Sell Signals</span>
            <span class="hero-badge amber">Crossovers</span>
        </div>
    </div>
    """,
        unsafe_allow_html=True,
    )

    st.markdown(
        """
    <div class="disclaimer">
    <strong>Analytical Disclaimer:</strong> These buy and sell signals are generated by a mechanical
    moving-average crossover rule. They are intended for exploratory analysis and educational
    demonstration only and do not account for costs, slippage, taxes, position sizing, or macro context.
    </div>
    """,
        unsafe_allow_html=True,
    )

    st.markdown("<div class='section-divider'></div>", unsafe_allow_html=True)

    col_a, col_b, col_c = st.columns(3)
    with col_a:
        ticker = st.selectbox("Select stock", TICKERS, format_func=lambda x: NAME_MAP[x])
    with col_b:
        short_w = st.selectbox("Short MA window", [10, 20, 50], index=2)
    with col_c:
        long_w = st.selectbox("Long MA window", [100, 200], index=1)

    if short_w >= long_w:
        st.warning("The short MA window must be smaller than the long MA window.")
        return

    sig_df = compute_signals(df, ticker, short_w, long_w)
    buy = sig_df[sig_df["position"] == 1]
    sell = sig_df[sig_df["position"] == -1]

    c1, c2, c3, c4 = st.columns(4)
    last_signal = "None"
    last_signal_color = "cyan"
    last_pos_row = sig_df[sig_df["position"] != 0].dropna(subset=["position"])
    if not last_pos_row.empty:
        last_row = last_pos_row.iloc[-1]
        signal_side = "BUY" if last_row["position"] == 1 else "SELL"
        last_signal = f"{signal_side} on {last_row['date'].strftime('%b %d, %Y')}"
        last_signal_color = "green" if last_row["position"] == 1 else "red"

    latest_close = sig_df["close"].iloc[-1] if len(sig_df) else 0

    with c1:
        st.markdown(f'<div class="kpi-card green"><div class="kpi-icon">BUY</div><div class="kpi-label">Total Buy Signals</div><div class="kpi-value">{len(buy)}</div><div class="kpi-delta">MA{short_w} crossed above MA{long_w}</div></div>', unsafe_allow_html=True)
    with c2:
        st.markdown(f'<div class="kpi-card red"><div class="kpi-icon">SELL</div><div class="kpi-label">Total Sell Signals</div><div class="kpi-value">{len(sell)}</div><div class="kpi-delta">MA{short_w} crossed below MA{long_w}</div></div>', unsafe_allow_html=True)
    with c3:
        st.markdown(f'<div class="kpi-card cyan"><div class="kpi-icon">PX</div><div class="kpi-label">Latest Close</div><div class="kpi-value">${latest_close:.2f}</div><div class="kpi-delta">{NAME_MAP[ticker]}</div></div>', unsafe_allow_html=True)
    with c4:
        st.markdown(f'<div class="kpi-card {last_signal_color}"><div class="kpi-icon">LAST</div><div class="kpi-label">Last Signal</div><div class="kpi-value" style="font-size:0.85rem">{last_signal}</div></div>', unsafe_allow_html=True)

    st.markdown("<div class='section-divider'></div>", unsafe_allow_html=True)
    st.markdown('<div class="chart-card"><div class="chart-title">MA Crossover Signal Chart</div><div class="chart-sub">Buy markers indicate bullish crossovers; sell markers indicate bearish crossovers</div>', unsafe_allow_html=True)
    st.plotly_chart(signal_chart(sig_df, ticker), use_container_width=True, config={"displayModeBar": False})
    st.markdown("</div>", unsafe_allow_html=True)

    col_l, col_r = st.columns(2)
    with col_l:
        st.markdown("##### Buy Signal Events")
        if not buy.empty:
            b_show = buy[["date", "close", "ma_short", "ma_long"]].copy()
            b_show.columns = ["Date", "Close ($)", f"MA{short_w}", f"MA{long_w}"]
            b_show["Date"] = b_show["Date"].dt.strftime("%Y-%m-%d")
            st.dataframe(b_show.round(2), use_container_width=True, hide_index=True)
        else:
            st.info("No buy signals were generated in the selected period.")
    with col_r:
        st.markdown("##### Sell Signal Events")
        if not sell.empty:
            s_show = sell[["date", "close", "ma_short", "ma_long"]].copy()
            s_show.columns = ["Date", "Close ($)", f"MA{short_w}", f"MA{long_w}"]
            s_show["Date"] = s_show["Date"].dt.strftime("%Y-%m-%d")
            st.dataframe(s_show.round(2), use_container_width=True, hide_index=True)
        else:
            st.info("No sell signals were generated in the selected period.")

    st.markdown(
        """
    <div class="insight-box cyan">
        <div class="insight-box-label">Signal Logic</div>
        <p>
        A Golden Cross occurs when the short-term moving average rises above the long-term average,
        while a Death Cross occurs when it falls below it. Shorter windows create more frequent but
        noisier signals; longer windows create fewer, slower, and more structural signals.
        </p>
    </div>
    """,
        unsafe_allow_html=True,
    )

    st.markdown("<div class='section-divider'></div>", unsafe_allow_html=True)
    st.markdown("#### Signal Summary - All Stocks")
    rows = []
    for t in TICKERS:
        s = compute_signals(df, t, short_w, long_w)
        b = s[s["position"] == 1]
        sl = s[s["position"] == -1]
        last_p = s[s["position"] != 0].dropna(subset=["position"])
        if not last_p.empty:
            lr = last_p.iloc[-1]
            last_sig_text = f"{'Buy' if lr['position'] == 1 else 'Sell'} | {lr['date'].strftime('%Y-%m-%d')}"
        else:
            last_sig_text = "None"
        rows.append(
            {
                "Company": NAME_MAP[t],
                "Buy Signals": len(b),
                "Sell Signals": len(sl),
                "Last Signal": last_sig_text,
            }
        )
    st.dataframe(pd.DataFrame(rows), use_container_width=True, hide_index=True)
